### ISSUE TITLE
Mod compatibility doesn't seem to work

### ISSUE THREAD

**Issue by Tepig125** [PvtFudgepants/Tmodloader-ColoredDamageTypes#1]
As of Colored Damage Types v1.7.1 on the latest stable build of tModLoader (v2022.4.62.6), the Mod.Call functionality appears to not properly register modded damage types and thus does not display those damage types' custom colors.
In my mod, I put the following code:
```cs
public override void PostSetupContent()
{
	if (ModLoader.TryGetMod("ColoredDamageTypes", out Mod cdt))
	{
		// As a note, I also tried using the tuple method. It didn't change anything
		cdt.Call(GetInstance<ArtistDamageClass>(), new Color(102, 242, 184), new Color(51, 121, 92), new Color(115, 255, 197));
	}
}
```
In-game, the class' weapons still display the default color in their tooltip, and the damage numbers still display the default color as well. Additionally, the config settings for modded damage types had no mention of my damage type, even after pressing the "restore defaults" button. As far as I can tell, all vanilla damage types work as intended, and it's only modded damage types that don't function.
I tried enabling the debug mode to see if it would tell me anything, and in the logs I was told that Colored Damage Types was listing my damage type (ArtistDamageClass) as "`Terraria.ModLoader.GenericDamageClass`". My best guess is that, for whatever reason, the Mod.Call doesn't add modded damage types to the list of damage types like it's intended to. That, or I just messed something up within my code, which is very possible as well.

**Comment by PvtFudgepants** [comment]
Try changing the call to 
```cs
cdt.Call("AddDamageType", GetInstance<ArtistDamageClass>(), new Color(102, 242, 184), new Color(51, 121, 92), new Color(115, 255, 197));
```
Should work that way. I forgot that I had added that change to have the first argument be a string _right_ before uploading it, so I never changed the readme.

**Comment by Tepig125** [comment]
Oh, that worked! Thank you!
